export const THEME_SETTINGS = 'THEME__SETTINGS__'
export const TOKEN_KEY = 'TOKEN__'
export const USER_INFO_KEY = 'USER__INFO__'
export const LANGUAGE__KEY = 'LANGUAGE__'
export const CACHE_ROUTES = 'CACHE_ROUTES__'
